version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "us-east-1"
    DLC_REGISTRY:  "763104351884.dkr.ecr.us-east-1.amazonaws.com"
    ECR_REGISTRY:  "891377318910.dkr.ecr.us-east-1.amazonaws.com"
    ECR_REPO:      "sm-batch-transform-triton-aws"
    IMAGE_TAG:     "latest"

phases:
  pre_build:
    commands:
      # Login na DLC ECR (para pull da imagem base)
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $DLC_REGISTRY
      # Login no nosso ECR (para push da imagem final)
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

  build:
    commands:
      - docker build -f app/triton_aws/Dockerfile -t $ECR_REPO:$IMAGE_TAG .

  post_build:
    commands:
      - docker tag $ECR_REPO:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG
      - docker push $ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG
      - printf '[{"name":"triton-aws","imageUri":"%s"}]' "$ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG" > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json

cache:
  paths:
    - /root/.docker/**/*
