name: "postprocess"
backend: "python"
max_batch_size: 8

input [
  {
    name: "record_id"
    data_type: TYPE_STRING
    dims: [1]
  },
  {
    name: "scores"
    data_type: TYPE_FP32
    dims: [6]
  }
]

output [
  {
    name: "record_id"
    data_type: TYPE_STRING
    dims: [1]
  },
  {
    name: "class_name"
    data_type: TYPE_STRING
    dims: [1]
  },
  {
    name: "score"
    data_type: TYPE_STRING
    dims: [1]
  }
]

instance_group [{ kind: KIND_CPU }]

dynamic_batching {
  preferred_batch_size: [2, 4, 8]
  max_queue_delay_microseconds: 3000000
}
