name: "preprocess"
backend: "python"
max_batch_size: 8

input [
  {
    name: "record_id"
    data_type: TYPE_STRING
    dims: [1]
  },
  {
    name: "image_s3_path"
    data_type: TYPE_STRING
    dims: [1]
  }
]

output [
  {
    name: "preprocessed"
    data_type: TYPE_FP32
    dims: [3, 256, 256]
  }
]

instance_group [{ kind: KIND_CPU }]

dynamic_batching {
  preferred_batch_size: [2, 4, 8]
  max_queue_delay_microseconds: 3000000
}
