name: "classifier"
backend: "onnxruntime"
max_batch_size: 8

input [
  {
    name: "input"
    data_type: TYPE_FP32
    dims: [3, 256, 256]
  }
]

output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [6]
  }
]

dynamic_batching {
  preferred_batch_size: [2, 4, 8]
  max_queue_delay_microseconds: 3000000
}
